import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { greyScale } from "@/utils/colors"
import { ThemeProvider } from "./ThemeProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ background: greyScale.grey1000, color: greyScale.grey0 }}
      >
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  )
}
