import type { Metadata } from "next"
import { Inter } from "next/font/google"
import localFont from "next/font/local"
import "./globals.css"
import { greyScale } from "@/utils/colors"
import { ThemeProvider } from "./ThemeProvider"
import { SmoothScroller } from "@/components/Providers/SmoothScroller"
import { TomoProvider } from "@/components/Providers/TomoProvider"

const inter = Inter({ subsets: ["latin"] })

// const mango = localFont({
//   src: [
//     {
//       path: "/assets/Fonts/MangoGrotesque-Medium.ttf",
//       weight: "500",
//       style: "normal",
//     },
//     {
//       path: "/assets/Fonts/MangoGrotesque-SemiBold.ttf",
//       weight: "600",
//       style: "normal",
//     },
//   ],
// })

export const metadata: Metadata = {
  title: "LiTED by Story",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}`}
        style={{ background: greyScale.grey1000, color: greyScale.grey0 }}
      >
        <TomoProvider>
          <SmoothScroller>
            <ThemeProvider>{children}</ThemeProvider>
          </SmoothScroller>
        </TomoProvider>
      </body>
    </html>
  )
}
